# Generated by Django 4.0.5 on 2022-07-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0002_alter_adduser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=250)),
                ('AvailableIN', models.CharField(max_length=250)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Adduser',
        ),
    ]
