# Generated by Django 4.0.5 on 2022-07-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0003_drinks_delete_adduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
            ],
        ),
    ]
