# Generated by Django 4.0.5 on 2022-07-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=250)),
                ('Category', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Food and Drink', 'Food and Drink'), ('Home', 'Home'), ('Life', 'Life'), ('Transport', 'Transport'), ('Utilities', 'Utilities'), ('General', 'General')], max_length=25)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
