# Generated by Django 4.0.5 on 2022-07-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0006_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city',
        ),
    ]
