# Generated by Django 4.0.5 on 2022-07-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0007_alter_city_options_rename_name_city_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
